build:
  version: "3.0"

accounts:
  message: "Welcome to eazybank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eaxybank.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-6789
