build:
  version: "2.0"

accounts:
  message: "Welcome to eazybank accounts related QA APIs"
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smith@eaxybank.com"
  onCallSupport:
    -(555)555-3424
    -(555)555-4543