build:
  version: "1.0"

loans:
  message: "Welcome to eazybank loans related prod APIs"
  contactDetails:
    name: "Rine Aishwarya - Developer"
    email: "aish@eaxybank.com"
  onCallSupport:
    -(555)555-4829
    -(555)555-4545